### ISSUE TITLE
Enable private vulnerability reporting in Security settings

### ISSUE THREAD

**Issue by sax** [redrabbit/git.limo#88]
Hello! I'm playing around with `gitrekt` on a personal project, and in doing so found a potential issue in `git_gud` that I'd like to report privately. GitHub recently shipped the ability to do so, but you have to enable it in the Security tab.

Anyway, thanks for all this code!

**Comment by sax** [comment]
Hi! I was wondering if you saw this. I'd really like to report a security vulnerability, but would prefer to do so privately so that you can deploy the fix.

**Comment by redrabbit** [comment]
Hi @sax and thanks for taking the time to report the issue. I just enabled private security reports for the repo.

**Comment by sax** [comment]
Thank you!
